require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/charges', type: :request do
  include Devise::Test::IntegrationHelpers
  let(:user) do
    User.create(
      name: 'Angel',
      email: 'angel@gmail.com',
      password: '1234567'
    )
  end

  describe 'GET /charges' do
    before do
      sign_in user
      get new_charge_path
    end

    it 'returns the right responds' do
      get '/charges/new'
      expect(response).to have_http_status(200)
    end

    it 'responds html' do
      expect(response.content_type).to include 'text/html'
    end
  end
end
