require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/relations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Relation. As you add validations to Relation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Relation.create! valid_attributes
      get relations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      relation = Relation.create! valid_attributes
      get relation_url(relation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_relation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      relation = Relation.create! valid_attributes
      get edit_relation_url(relation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Relation" do
        expect {
          post relations_url, params: { relation: valid_attributes }
        }.to change(Relation, :count).by(1)
      end

      it "redirects to the created relation" do
        post relations_url, params: { relation: valid_attributes }
        expect(response).to redirect_to(relation_url(Relation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Relation" do
        expect {
          post relations_url, params: { relation: invalid_attributes }
        }.to change(Relation, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post relations_url, params: { relation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested relation" do
        relation = Relation.create! valid_attributes
        patch relation_url(relation), params: { relation: new_attributes }
        relation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the relation" do
        relation = Relation.create! valid_attributes
        patch relation_url(relation), params: { relation: new_attributes }
        relation.reload
        expect(response).to redirect_to(relation_url(relation))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        relation = Relation.create! valid_attributes
        patch relation_url(relation), params: { relation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested relation" do
      relation = Relation.create! valid_attributes
      expect {
        delete relation_url(relation)
      }.to change(Relation, :count).by(-1)
    end

    it "redirects to the relations list" do
      relation = Relation.create! valid_attributes
      delete relation_url(relation)
      expect(response).to redirect_to(relations_url)
    end
  end
end
